In [ ]:
import pandas as pd
/

In [5]:
car_data = pd.read_csv(r'/home/akogo/Desktop/RGT-Data-Analyst-Capst/car_price_prediction.csv')

In [6]:
# Data Cleaning

# Convert 'Levy' and 'Mileage' columns to numeric, replacing non-numeric characters
car_data['Levy'] = pd.to_numeric(car_data['Levy'], errors='coerce')
car_data['Mileage'] = car_data['Mileage'].str.replace(' km', '').astype(float)

# Dropping irrelevant columns (e.g., ID and Model)
car_data = car_data.drop(['ID', 'Model'], axis=1)

# Convert categorical columns to numeric using one-hot encoding
car_data = pd.get_dummies(car_data, drop_first=True)

# Drop rows with missing values
car_data = car_data.dropna()

# Display the cleaned data
car_data.head()

,Price,Levy,Prod. year,Mileage,Cylinders,Airbags,Manufacturer_ALFA ROMEO,Manufacturer_ASTON MARTIN,Manufacturer_AUDI,Manufacturer_BENTLEY,...,Color_Green,Color_Grey,Color_Orange,Color_Pink,Color_Purple,Color_Red,Color_Silver,Color_Sky blue,Color_White,Color_Yellow
0,13328,1399.0,2010,186005.0,6.0,12,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,16621,1018.0,2011,192000.0,6.0,8,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3607,862.0,2011,168966.0,4.0,0,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,11726,446.0,2014,91901.0,4.0,4,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
5,39493,891.0,2016,160931.0,4.0,4,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Split the data into features and target variable
X = car_data.drop('Price', axis=1)
y = car_data['Price']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

rmse, r2

(13619.189305698623, 0.38468399267172626)